# vim: ft=toml

theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "custom"
cycle = ["bash ~/.config/i3/tun_dir.bash 0 int", "bash ~/.config/i3/tun_dir.bash 0 add"]
on_click = "<command>"
interval = 5

[[block]]
block = "custom"
cycle = ["bash ~/.config/i3/tun_dir.bash 1 int", "bash ~/.config/i3/tun_dir.bash 1 add"]
on_click = "<command>"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 30
show = "both"

[[block]]
block = "pacman"
interval = 1800

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
