#!/usr/bin/bash

function find_state () {

    local result=$(xrandr | awk -v s=${SCREEN} '{if( $1 ~ s ) print $3 }')

    if [[ $result == "(normal" ]]
    then
        STATE=off
    else
        STATE=on
    fi

}


function check_connection () {

    CONNECTION=$(xrandr | grep "${SCREEN}" | awk '{print $2}')

    if [[ $CONNECTION == "disconnected" ]]
    then
        echo "Screen is disconnected, try plugging in..."
        exit
    fi

}

SCREEN="${1}"
check_connection
find_state

case $STATE in
    off)
        # The we turn it on
        xrandr --output ${SCREEN} --mode 1280x720 --above eDP1
        bash ~/.config/i3/set-audio-profile hdmi;;
    on)
        # Then we turn it off
        xrandr --output ${SCREEN} --off
        bash ~/.config/i3/set-audio-profile default;;
esac
