#!/usr/bin/bash

# Sinks
# alsa_output.pci-0000_00_1f.3.hdmi-stereo
# alsa_output.pci-0000_00_1f.3.analog-stereo
#
# Sources
# alsa_input.pci-0000_00_1f.3.analog-stereo


function profile-hdmi () {
    PROFILE=output:hdmi-stereo+input:analog-stereo
}

function profile-default () {
    PROFILE=output:analog-stereo+input:analog-stereo
}

profile="${1}"

case $profile in
    hdmi)
        profile-hdmi;;
    *)
        profile-default;;
esac

pactl set-card-profile 0 $PROFILE
