# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Bindings for normal mode
# config.bind(';M', 'hint --rapid links spawn mpv {hint-url}')
config.bind(';M', 'hint url spawn umpv --title=hdmi_qb {hint-url}')
config.bind('<Ctrl+m>', 'spawn mpv {url}')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('j', 'scroll up')
config.bind('k', 'scroll down')
config.bind('<Alt+q>', 'set-cmd-text -s :quickmark-load -t')
# Bindings for hint mode
# config.bind(';M', 'spawn mpv {hint-url}', mode='hint')
